-- LAB1 - Banco de Dados
-- GABRIEL HENRIQUE CAMPOS SCALICI 9292970
--

-- ***** CRIACAO DAS PRINCIPAIS TABELAS NO EXERCICIO

---- TIME
--CREATE TABLE CLUBE (
--    NOME_CLUBE VARCHAR2(20) NOT NULL PRIMARY KEY,
--    ESTADO CHAR(2),
--    TIPO VARCHAR(12) CHECK (TIPO IN ('AMADOR', 'PROFISSIONAL')),
--    SALDO_GOL NUMBER
--);
--
---- JOGA
--CREATE TABLE JOGA (
--    TIME1 VARCHAR2(20)NOT NULL,
--    TIME2 VARCHAR2(20)NOT NULL,    
--    CLASSICO CHAR(1),
--    
--    CONSTRAINT PK_JOGA PRIMARY KEY(TIME1, TIME2), 
--    CONSTRAINT FK_TIME1 FOREIGN KEY (TIME1)
--                        REFERENCES CLUBE(NOME_CLUBE)
--                        ON DELETE CASCADE,
--    CONSTRAINT FK_TIME2 FOREIGN KEY (TIME2)
--                        REFERENCES CLUBE(NOME_CLUBE)
--                        ON DELETE CASCADE,
--    
--    --VERIFICANDO SE OS TIMES SAO DIFERENTES
--    CONSTRAINT CLUBES_DIFERENTES_JOGA CHECK (TIME1 != TIME2)
--);
------
---- PARTIDA
--CREATE TABLE PARTIDA (
--    TIME1 VARCHAR2(20)NOT NULL,
--    TIME2 VARCHAR2(20)NOT NULL,
--    DATA_PARTIDA DATE NOT NULL,
--    PLACAR CHAR(3) DEFAULT '0X0',
--    LOCAL_JOGO VARCHAR2(25),
--    
--    
--    CONSTRAINT PK_PARTIDA PRIMARY KEY(TIME1, TIME2, DATA_PARTIDA),
--    CONSTRAINT FK_TIMES FOREIGN KEY (TIME1, TIME2)
--                        REFERENCES JOGA(TIME1, TIME2)
--                        ON DELETE CASCADE
--                    
--);
--
---- JOGADOR
--CREATE TABLE JOGADOR (
--    CPF_JOGADOR VARCHAR2(20) NOT NULL PRIMARY KEY,
--    RG_JOGADOR VARCHAR2(10) NOT NULL UNIQUE,
--    NOME_JOGADOR VARCHAR2(25) NOT NULL UNIQUE,
--    DATA_NASC_JOGADOR DATE,
--    NATURALIDADE_JOGADOR VARCHAR2(10),
--    TIME_JOGADOR VARCHAR2(20) NOT NULL,
--    
--    CONSTRAINT FK_TIME FOREIGN KEY (TIME_JOGADOR)
--                       REFERENCES CLUBE(NOME_CLUBE)
--                       ON DELETE SET NULL
--    
--);
--
---- POSICAO
--CREATE TABLE POSICAO (
--    POSICAO_JOGADOR VARCHAR2(15) NOT NULL,
--    CPF_JOGADOR VARCHAR(20) NOT NULL,
--    
--    CONSTRAINT PK_POSICAO PRIMARY KEY (POSICAO_JOGADOR, CPF_JOGADOR),
--    CONSTRAINT FK_POSICAO FOREIGN KEY (CPF_JOGADOR)
--                          REFERENCES JOGADOR(CPF_JOGADOR)
--                          ON DELETE CASCADE
--
--);
--
---- DIRETOR
--CREATE TABLE DIRETOR (
--    NOME_DIRETOR VARCHAR2(25) NOT NULL,
--    NOME_TIME VARCHAR(20) NOT NULL,
--    
--    CONSTRAINT PK_DIRETOR PRIMARY KEY (NOME_DIRETOR, NOME_TIME),
--    CONSTRAINT FK_DIRETOR FOREIGN KEY (NOME_TIME)
--                          REFERENCES CLUBE(NOME_CLUBE)
--                          ON DELETE CASCADE
--
--);
--
---- UNIFORME
--CREATE TABLE UNIFORME(
--    NOME_TIME VARCHAR2(20) NOT NULL,
--    TIPO_UNIFORME CHAR(7) NOT NULL CHECK (TIPO_UNIFORME IN ('TITULAR', 'RESERVA')),
--    COR_PRINCIPAL VARCHAR2(15),
--    
--    CONSTRAINT PK_UNIFORME PRIMARY KEY (NOME_TIME, TIPO_UNIFORME),
--    CONSTRAINT FK_UNIFORME FOREIGN KEY (NOME_TIME)
--                          REFERENCES CLUBE(NOME_CLUBE)
--                          ON DELETE CASCADE
--
--);

-- *** INSERCOES EXIGIDAS PELA PROFESSORA ***

-- ********* CLUBE ********
--INSERT INTO CLUBE (NOME_CLUBE, ESTADO, TIPO, SALDO_GOL)
--VALUES ('SAO PAULO', 'SP', 'PROFISSIONAL', 2);

--INSERT INTO CLUBE (NOME_CLUBE, ESTADO, TIPO, SALDO_GOL)
--VALUES ('PALMEIRAS', 'SP', 'PROFISSIONAL', 2);

--INSERT INTO CLUBE (NOME_CLUBE, ESTADO, TIPO, SALDO_GOL)
--VALUES ('GREMIO', 'RS', 'PROFISSIONAL', 2);

--INSERT INTO CLUBE (NOME_CLUBE, ESTADO, TIPO, SALDO_GOL)
--VALUES ('INTERNACIONAL', 'RS', 'PROFISSIONAL', 2);

--INSERT INTO CLUBE (NOME_CLUBE, ESTADO, TIPO, SALDO_GOL)
--VALUES ('ATITIA', 'SC', 'AMADOR', 2);
-- COM ERRO
--INSERT INTO CLUBE (NOME_CLUBE, ESTADO, TIPO, SALDO_GOL)
--VALUES ('ATITIA', 'SC', 'VARZEA', 2);


-- ****** JOGA ******
--INSERT INTO JOGA (TIME1, TIME2, CLASSICO)
--VALUES ('PALMEIRAS', 'SAO PAULO', '1');

--INSERT INTO JOGA (TIME1, TIME2, CLASSICO)
--VALUES ('INTERNACIONAL', 'GREMIO', '1');

--INSERT INTO JOGA (TIME1, TIME2, CLASSICO)
--VALUES ('PALMEIRAS', 'GREMIO', '0');

--INSERT INTO JOGA (TIME1, TIME2, CLASSICO)
--VALUES ('PALMEIRAS', 'INTERNACIONAL', '0');
--COM ERRO
--INSERT INTO JOGA (TIME1, TIME2, CLASSICO)
--VALUES ('PALMEIRAS', 'NACIONAL', '0');


-- **** DIRETOR *****
--INSERT INTO DIRETOR (NOME_DIRETOR, NOME_TIME)
--VALUES ('KAREN', 'INTERNACIONAL');

--INSERT INTO DIRETOR (NOME_DIRETOR, NOME_TIME)
--VALUES ('GABRIEL', 'SAO PAULO');

--INSERT INTO DIRETOR (NOME_DIRETOR, NOME_TIME)
--VALUES ('LURY', 'PALMEIRAS')
--COM ERRO
--INSERT INTO DIRETOR (NOME_DIRETOR, NOME_TIME)
--VALUES ('LUIS', 'PALMEI');


--********** JOGADOR ********
--INSERT INTO JOGADOR (CPF_JOGADOR,RG_JOGADOR, NOME_JOGADOR, DATA_NASC_JOGADOR, NATURALIDADE_JOGADOR, TIME_JOGADOR)
--VALUES ('45567898765', '344455678', 'FABIO', '23/11/98', 'BRASIL', 'SÃO PAULO');

--INSERT INTO JOGADOR (CPF_JOGADOR,RG_JOGADOR, NOME_JOGADOR, DATA_NASC_JOGADOR, NATURALIDADE_JOGADOR, TIME_JOGADOR)
--VALUES ('45537898765', '344453678', 'CARLOS', '23/11/98', 'BRASIL', 'PALMEIRAS');

--INSERT INTO JOGADOR (CPF_JOGADOR,RG_JOGADOR, NOME_JOGADOR, DATA_NASC_JOGADOR, NATURALIDADE_JOGADOR, TIME_JOGADOR)
--VALUES ('678053125785', '311453678', 'SALVADOR', '23/11/98', 'BRASIL', 'PALMEIRAS');

--INSERT INTO JOGADOR (CPF_JOGADOR,RG_JOGADOR, NOME_JOGADOR, DATA_NASC_JOGADOR, NATURALIDADE_JOGADOR, TIME_JOGADOR)
--VALUES ('678000125785', '000453678', 'CAMPOS', '23/11/98', 'BRASIL', 'SAO PAULO');
--COM ERRO
--INSERT INTO JOGADOR (CPF_JOGADOR,RG_JOGADOR, NOME_JOGADOR, DATA_NASC_JOGADOR, NATURALIDADE_JOGADOR, TIME_JOGADOR)
--VALUES ('678000125785', '000453678', 'CAMPOS', '23/11/98', 'BRASIL', 'SAOPAULO');

--INSERT INTO JOGADOR (CPF_JOGADOR,RG_JOGADOR, NOME_JOGADOR, DATA_NASC_JOGADOR, NATURALIDADE_JOGADOR, TIME_JOGADOR)
--VALUES ('678000125785', '000453678', 'CAMPOS', '23/11/98', 'BRASIL', 'PALMEIRAS');

-- ********* PARTIDA ********

--INSERT INTO PARTIDA (TIME1, TIME2, DATA_PARTIDA, PLACAR, LOCAL_JOGO)
--       VALUES ('PALMEIRAS', 'SAO PAULO', '09/01/1996', '1X2','MORUMBI');

--INSERT INTO PARTIDA (TIME1, TIME2, DATA_PARTIDA, PLACAR, LOCAL_JOGO)
--       VALUES ('PALMEIRAS', 'GREMIO', '09/01/1996', '1X2','MORUMBI');

--INSERT INTO PARTIDA (TIME1, TIME2, DATA_PARTIDA, PLACAR, LOCAL_JOGO)
--       VALUES ('INTERNACIONAL', 'GREMIO', '09/01/1996', '4X2','MORUMBI');

--INSERT INTO PARTIDA (TIME1, TIME2, DATA_PARTIDA, PLACAR, LOCAL_JOGO)
--       VALUES ('PALMEIRAS', 'INTERNACIONAL', '10/11/2000', '4X2','PACAEMBU');
--COM ERRO
--INSERT INTO PARTIDA (TIME1, TIME2, DATA_PARTIDA, PLACAR, LOCAL_JOGO)
--       VALUES ('CORINTHIANS', 'INTERNACIONAL', '10/11/2000', '4X2','PACAEMBU');
--
--INSERT INTO PARTIDA (TIME1, TIME2, DATA_PARTIDA, PLACAR, LOCAL_JOGO)
--       VALUES ('INTERNACIONAL', 'PALMEIRAS', '10/11/2000', '4X2','PACAEMBU');

--INSERT INTO PARTIDA (TIME1, TIME2, DATA_PARTIDA, PLACAR, LOCAL_JOGO)
--       VALUES ('PALMEIRAS', 'GREMIO', '10/11/2000', '4X2','PACAEMBU');

--******* POSICAO ********

--INSERT INTO POSICAO (POSICAO_JOGADOR, CPF_JOGADOR)
--        VALUES('LATERAL', '45567898765');

--INSERT INTO POSICAO (POSICAO_JOGADOR, CPF_JOGADOR)
--        VALUES('ATACANTE', '45537898765');

--INSERT INTO POSICAO (POSICAO_JOGADOR, CPF_JOGADOR)
--        VALUES('GOLEIRO', '678053125785');

--INSERT INTO POSICAO (POSICAO_JOGADOR, CPF_JOGADOR)
--        VALUES('GOLEIRO', '678000125785');

--COM ERRO
--INSERT INTO POSICAO (POSICAO_JOGADOR, CPF_JOGADOR)
--        VALUES('LATERAL', '6780025785');

-- ***** UNIFORME *******

--INSERT INTO UNIFORME (NOME_TIME, TIPO_UNIFORME, COR_PRINCIPAL)
--        VALUES ('SAO PAULO', 'TITULAR', 'VERMELHO');

--INSERT INTO UNIFORME (NOME_TIME, TIPO_UNIFORME, COR_PRINCIPAL)
--        VALUES ('SAO PAULO', 'RESERVA', 'BRANCO');

--INSERT INTO UNIFORME (NOME_TIME, TIPO_UNIFORME, COR_PRINCIPAL)
--        VALUES ('PALMEIRAS', 'RESERVA', 'BRANCO');

--INSERT INTO UNIFORME (NOME_TIME, TIPO_UNIFORME, COR_PRINCIPAL)
--        VALUES ('PALMEIRAS', 'TITULAR', 'VERDE');

--INSERT INTO UNIFORME (NOME_TIME, TIPO_UNIFORME, COR_PRINCIPAL)
--        VALUES ('INTERNACIONAL', 'TITULAR', 'VERMELHO');

--INSERT INTO UNIFORME (NOME_TIME, TIPO_UNIFORME, COR_PRINCIPAL)
--        VALUES ('GREMIO', 'TITULAR', 'AZUL');

--COM ERRO
--INSERT INTO UNIFORME (NOME_TIME, TIPO_UNIFORME, COR_PRINCIPAL)
--        VALUES ('GREMIO', 'TITULAR', 'VERDE');

--INSERT INTO UNIFORME (NOME_TIME, TIPO_UNIFORME, COR_PRINCIPAL)
--        VALUES ('CHAPECOENSE', 'TITULAR', 'VERDE');


-- **** ALTERACOES NECESSARIAS *********

-- 1
-- COR COMO ATRIBUTO MULTIVALORADO -> SOLUCAO: UMA NOVA TABELA

--ALTER TABLE UNIFORME DROP COLUMN COR_PRINCIPAL;

--CREATE TABLE CORES_UNIFORME(
--    NOME_TIME VARCHAR2(20) NOT NULL,
--    TIPO_UNIFORME CHAR(7) NOT NULL,
--    COR_UNIFORME VARCHAR2(10) NOT NULL,
--    
--    CONSTRAINT PK_CORES_UNIFOMRE PRIMARY KEY (NOME_TIME, TIPO_UNIFORME, COR_UNIFORME),
--    CONSTRAINT FK_CORES_UNIFORME FOREIGN KEY (NOME_TIME, TIPO_UNIFORME)
--                          REFERENCES UNIFORME(NOME_TIME, TIPO_UNIFORME)
--                          ON DELETE CASCADE
--
--);
--
-- INSERT INTO CORES_UNIFORME(NOME_TIME, TIPO_UNIFORME, COR_UNIFORME)
--        VALUES ('SAO PAULO', 'TITULAR', 'VERMELHO')
       
--INSERT INTO CORES_UNIFORME(NOME_TIME, TIPO_UNIFORME, COR_UNIFORME)
--        VALUES ('SAO PAULO', 'TITULAR', 'BRANCO')
     
--INSERT INTO CORES_UNIFORME(NOME_TIME, TIPO_UNIFORME, COR_UNIFORME)
--        VALUES ('SAO PAULO', 'TITULAR', 'PRETO')

-- 2
-- EDERECO NA TABELA JOGADOR PODE ASSUMIR O VALOR NULO

-- ALTER TABLE JOGADOR ADD ENDERECO VARCHAR2(20)

-- EXPLICACAO: PARA AS TUPLAS EXISTENTES, FOI CRIADO APENAS UM CAMPO A MAIS (ENDERECO) COM O VALOR NULO

-- 3
-- MESMA COISA QUE O ITEM 2 POREM UM UM ATRIBUTO QUE TENHA UM VALOR DEFAULT

--ALTER TABLE JOGADOR ADD SALARIO VARCHAR2(20) DEFAULT '3000,00';

-- EXPLICACAO: DIFERENTE DO  ITEM 2, PARA AS TUPLAS JÁ EXISTENTES, FOI CRIADO UM ATRIVUTO (SALARIO) COM O VALOR DEFINIDO POR DEFAULT

-- 4
-- REMOVER O ATRIVUTO CPF DA TABELA JOGADORES
-- COM ERRO
--ALTER TABLE JOGADOR DROP COLUMN CPF_JOGADOR;

-- EXPLICACAO: PARA MINHA IMPLEMENTACAO, NAO COLOQUEI FUNCIONAMENTO ESPECÍFICO PARA A CHAVE PRIMARIA, JUSTAMENTE PARA QUE NAO POSSA SER DELETADA

