---- Q1
--SELECT TIME1, TIME2, DATA
--FROM PARTIDA
--WHERE DATA > SYSDATE;

---- Q2
-- SELECT P.DATA, P.PLACAR, P.TIME1, P.TIME2, TA.ESTADO, TB.ESTADO
-- FROM PARTIDA P, TIME TA, TIME TB
-- WHERE P.TIME1 = TA.NOME AND P.TIME2 = TB.NOME;

---- Q3
-- Uma das unicas mudancas é que possui a identificacao para mais uma tabela, sendo necessario
-- checar novamente o time 1 e dois na tabela JOGA que contem a informacao se o jogo é classico
-- SELECT P.DATA, P.PLACAR, P.TIME1, P.TIME2, TA.ESTADO, TB.ESTADO, J.CLASSICO
-- FROM PARTIDA P, TIME TA, TIME TB, JOGA J
-- WHERE P.TIME1 = TA.NOME AND P.TIME2 = TB.NOME AND P.TIME1 = J.TIME1 AND P.TIME2 = J.TIME2;

---- Q4
-- Funcao extract usada com and para ano e mes separadamente
-- SELECT COUNT(J.CLASSICO)
-- FROM PARTIDA P, JOGA J
-- WHERE P.TIME1 = J.TIME1 AND P.TIME2 = J.TIME2 AND
-- (EXTRACT(MONTH FROM TO_DATE(DATA, 'DD-MM-RR')) = 02) AND (EXTRACT(YEAR FROM TO_DATE(DATA, 'DD-MM-RR')) = 2018);

---- Q5
-- SELECT ESTADO, AVG(SALDO_GOLS) AS MEDIA
-- FROM TIME
-- GROUP BY ESTADO
-- ORDER BY ESTADO;

---- Q6
-- SELECT ESTADO, COUNT(NOME) AS QUANTIDADE_TIMES, AVG(SALDO_GOLS) AS MEDIA
-- FROM TIME
-- GROUP BY ESTADO
-- ORDER BY ESTADO;

---- Q7
---- ORDENADO POR TIPO
-- SELECT ESTADO, AVG(SALDO_GOLS) AS MEDIA
-- FROM TIME
-- GROUP BY ESTADO, TIPO
-- ORDER BY TIPO;

---- ORDENADO POR ESTADO
-- SELECT ESTADO, AVG(SALDO_GOLS) AS MEDIA
-- FROM TIME
-- GROUP BY ESTADO, TIPO
-- ORDER BY ESTADO;

---- Q8
-- SELECT ESTADO, AVG(SALDO_GOLS) AS MEDIA
-- FROM TIME WHERE TIPO = 'PROFISSIONAL' AND SALDO_GOLS >=1
-- GROUP BY ESTADO
-- ORDER BY ESTADO;

---- Q9
-- SELECT ESTADO, AVG(SALDO_GOLS) AS MEDIA
-- FROM TIME
-- WHERE TIPO = 'PROFISSIONAL'
-- GROUP BY ESTADO
-- HAVING COUNT(*) > 1
-- ORDER BY ESTADO;

---- Q10
---- Nao tinha nenhuma insercao com essas restricoes, entao foi necessario fazer um novo insert para teste
-- SELECT ESTADO, AVG(SALDO_GOLS) AS MEDIA
-- FROM TIME
-- WHERE TIPO = 'PROFISSIONAL'
-- GROUP BY ESTADO
-- HAVING AVG(SALDO_GOLS) > 5 AND AVG(SALDO_GOLS)  < 15
-- ORDER BY ESTADO;

---- Q11
